In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import yfinance as yf

In [4]:
def get_prices(symbol: str, period: str = "1y", interval: str = "1d"):
    df = yf.download(
        tickers=symbol,
        period=period,
        interval=interval,
        auto_adjust=True,
        progress=False,
        threads=False,
    )
    return df

In [5]:
get_prices("AAPL")

1 Failed download:
['AAPL']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Empty DataFrame
Columns: [(Adj Close, AAPL), (Close, AAPL), (High, AAPL), (Low, AAPL), (Open, AAPL), (Volume, AAPL)]
Index: []

In [6]:
data = yf.download("AAPL MSFT GOOG", start="2023-01-01", end="2023-01-10")

[*********************100%***********************]  3 of 3 completed

3 Failed downloads:
['AAPL', 'GOOG', 'MSFT']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

In [7]:
data

Empty DataFrame
Columns: [(Adj Close, AAPL), (Adj Close, GOOG), (Adj Close, MSFT), (Close, AAPL), (Close, GOOG), (Close, MSFT), (High, AAPL), (High, GOOG), (High, MSFT), (Low, AAPL), (Low, GOOG), (Low, MSFT), (Open, AAPL), (Open, GOOG), (Open, MSFT), (Volume, AAPL), (Volume, GOOG), (Volume, MSFT)]
Index: []

In [9]:
msft = yf.Ticker("MSFT")
# Get history for this specific ticker
hist = msft.history(period="max")

YFRateLimitError: Too Many Requests. Rate limited. Try after a while.

In [10]:
ticker = 'AAPL'
data = yf.download(ticker, start='2020-01-01', end='2023-01-01')

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AAPL']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')